# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gramsetu
spring.datasource.username=postgres
spring.datasource.password=Pruthviraj@1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8081
spring.application.name=gramsetu

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# JWT
jwt.secret=gramsetu_super_secret_key_must_be_32chars!
jwt.expiration-ms=86400000

spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.SQL=DEBUG


msg91.auth.key=547982A3dVyLYVDfEN6a4b8029P1
msg91.template.id=6a4b7f1217e08fe68003b222
msg91.sender.id=GRMSETU

razorpay.key.id=rzp_test_TAGHgMwt5e7CMl
razorpay.key.secret=Z6IfcUXrXu0zdxZDbRowPi8r


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gramsetuportal@gmail.com
spring.mail.password=yzah pehn kodo auga
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
